### ISSUE TITLE
Lighthouse score needs improvement

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [freearhey/web-learn#11]
I have taken a screenshot of your website's lighthouse score. It could be improve in accessibility & SEO. If you agree, I could work on these issues & submit a PR. Let me know @freearhey 

**_Lighthouse score screenshot below:_**

![lighthouse-score](https://user-images.githubusercontent.com/32891808/60764049-48750580-a04f-11e9-8b79-a8c4c5c43ff6.jpg)

**Comment by freearhey** [comment]
Sure I do!

**Comment by Manuel-Suarez-Abascal** [comment]
> Sure I do!

Awesome, I'll work on it this week! :)

**Comment by Manuel-Suarez-Abascal** [comment]
@freearhey I am trying to run the project in my local machine, but I get this error:

![error](https://user-images.githubusercontent.com/32891808/60915703-7ed2a080-a25a-11e9-89a8-f0f02815410d.jpg)

Any idea how to solve this?

**Comment by freearhey** [comment]
You just need to create a .env.local file in the project folder with the API Data YouTube API key:

```
export const YOUTUBE_API_KEY = YOUR_API_KEY_HERE
```

The key can be obtained via Google API Console: https://console.developers.google.com/

**Comment by freearhey** [comment]
Resolved.
