### ISSUE TITLE
Website doesn't follow responsive design in mobile

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [freearhey/web-learn#12]
The mobile version of the site is not responsive. We are not able to click other **study categories** or the **github & tweet buttons**. I have attached a screenshot below showcasing this issue. I could work on it. Let me know @freearhey :)

**_Mobile View Screenshot:_**
![mobile-view-grid](https://user-images.githubusercontent.com/32891808/60764127-5cba0200-a051-11e9-8987-188828639a12.jpg)

**Comment by freearhey** [comment]
It would be great!
