### ISSUE TITLE
Unable to install it completely. I did following step :

### ISSUE THREAD

**Issue by Manishfoodtechs** [freearhey/web-learn#17]
Unable to install it completely. I did following step :
1. I am using my own Youtube API Key.
2. I am Using google verified domain html. 
3. Did npm install 
4. I got this 
![image](https://user-images.githubusercontent.com/29369645/66650369-11b21b00-ec4e-11e9-96ee-9998963899c5.png)

What else I have to run to make it work . Please help .

I am early stage of learning coding.

**Comment by freearhey** [comment]
Did you run `npm run dev` on the command line?

**Comment by freearhey** [comment]
Just in case, I added step-by-step installation instructions to the documentation: https://github.com/freearhey/web-learn#development
