### ISSUE TITLE
Request Failed with status code 400

### ISSUE THREAD

**Issue by mohsin1122** [freearhey/web-learn#18]
when i run the site the error toast appears saying
Error: Request Failed with status code 400
i have valid youtube key

**Comment by freearhey** [comment]
And this is after you have completed all the steps from this guide: https://github.com/freearhey/web-learn#development?

**Comment by mohsin1122** [comment]
yes
i have completed all the steps as mentioned in the guide

**Comment by freearhey** [comment]
I just checked the code again, and it works fine for me. So the problem is most likely in the API key, because error 400 means that the request is incorrect. 

I can only advise you to make a request directly to the YouTube API and check the response yourself: `https://www.googleapis.com/youtube/v3/search?q=js&type=video&part=snippet&key=YOUR_API_KEY_HERE`

**Comment by mohsin1122** [comment]
i am getting the response with my API Key
`{
 "kind": "youtube#searchListResponse",
 "etag": "\"j6xRRd8dTPVVptg711_CSPADRfg/RvDulO7gOGDkfPf5ObFuymaQtDg\"",
 "nextPageToken": "CAUQAA",
 "regionCode": "PK",
 "pageInfo": {
  "totalResults": 1000000,
  "resultsPerPage": 5
 },
 "items": [
  {
   "kind": "youtube#searchResult",
   "etag": "\"j6xRRd8dTPVVptg711_CSPADRfg/jotAwaum2w0wd9ALBGSP999KwdY\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "Af6HM5ySqaE"
   },
   "snippet": {
    "publishedAt": "2019-11-13T03:30:00.000Z",
    "channelId": "UC0VN6My1ueOFXDTgzMZSSNQ",
    "title": "my DIRTY Secret",
    "description": "Get my Sunglasses from EyewearLabs: https://goo.gl/8oZwgH My MERCH: https://bit.ly/2DedHWW OFFICIAL WEBSITE: https://jaysnnation.com ADD ME ON: ...",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/Af6HM5ySqaE/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/Af6HM5ySqaE/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/Af6HM5ySqaE/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "JS Films",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"j6xRRd8dTPVVptg711_CSPADRfg/2LQloPyi8shASTvQcL2scGmipqo\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "lUn2-8AYQes"
   },
   "snippet": {
    "publishedAt": "2018-06-03T23:26:47.000Z",
    "channelId": "UC_h_oDzRLXagKsNhkrPmcmQ",
    "title": "JS Pakistan - Matrimonial Social Project for Pakistani Community !",
    "description": "JS Pakistan - www.jspakistan.com - is the Pakistani best matrimonial website where 100% serious and needy Pakistani Rishta registered. We are doing social ...",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/lUn2-8AYQes/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/lUn2-8AYQes/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/lUn2-8AYQes/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "JS Pakistan",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"j6xRRd8dTPVVptg711_CSPADRfg/cPH5Yeq_gnORZXFlhffLJhDuUH4\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "nYXEtVRu3RM"
   },
   "snippet": {
    "publishedAt": "2019-01-23T06:00:02.000Z",
    "channelId": "UCJM1Zt7njtHWv_-awBMlgrg",
    "title": "BURNOUT GONE WRONG ft.JS Films !! 😎😎😎",
    "description": "For Business/Collaborations :- ➡ ypm.vlogs@trending-tenor.com ▷ Instagram :- ➡ https://www.instagram.com/ypmvlogs ▷ Song Credits ...",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/nYXEtVRu3RM/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/nYXEtVRu3RM/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/nYXEtVRu3RM/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "YPM Vlogs",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"j6xRRd8dTPVVptg711_CSPADRfg/4NzD8JwEzQfY7fzN71ENYJsK70U\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "0P5fA3kAWGE"
   },
   "snippet": {
    "publishedAt": "2018-07-18T06:42:46.000Z",
    "channelId": "UChitjK6PnW5WnyW9Iqc9lWg",
    "title": "JS Films FIGHT WITH | GAURAVZONE |",
    "description": "SHARE This video to with your friends and subscribe my YouTube channel and don't forget Like this video 🤣🤔",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/0P5fA3kAWGE/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/0P5fA3kAWGE/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/0P5fA3kAWGE/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Haryanvi Yadav",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"j6xRRd8dTPVVptg711_CSPADRfg/aQEiDKP_cF0UkQjQnYeA836TkH8\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "pJSQ9RkdmBI"
   },
   "snippet": {
    "publishedAt": "2019-08-26T04:30:01.000Z",
    "channelId": "UC0VN6My1ueOFXDTgzMZSSNQ",
    "title": "INDIA&#39;s only Road Legal CHOPPER !!",
    "description": "Avanturaa Choppers: http://bit.ly/2HEd0bt My MERCH: https://bit.ly/2DedHWW OFFICIAL WEBSITE: https://jaysnnation.com ADD ME ON: INSTAGRAM: ...",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/pJSQ9RkdmBI/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/pJSQ9RkdmBI/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/pJSQ9RkdmBI/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "JS Films",
    "liveBroadcastContent": "none"
   }
  }
 ]
}`

**Comment by mohsin1122** [comment]
this is the logs from Cmd

`>npm run dev

> web-learn@ dev D:\Projects\web-learn
> webpack-dev-server --inline --hot

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /build/
i ｢wds｣: Content not from webpack is served from D:\Projects\web-learn
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /build/bundle.js
i ｢wdm｣: Hash: 42b7e31798f7e4e89bb1
Version: webpack 4.39.2
Time: 7876ms
Built at: 11/15/2019 11:48:53 AM
                                                                                Asset      Size                                                                       Chunks             Chunk Names
                                                                            bundle.js  3.52 MiB                                                                         main  [emitted]  main
                                                              channel-about.bundle.js  30.5 KiB                                                                channel-about  [emitted]  channel-about
                                                             channel-videos.bundle.js  57.1 KiB                                                               channel-videos  [emitted]  channel-videos
                      channel-videos~index~search~single-video~topic-videos.bundle.js   289 KiB                        channel-videos~index~search~single-video~topic-videos  [emitted]  channel-videos~index~search~single-video~topic-videos
                                                                      index.bundle.js  81.1 KiB                                                                        index  [emitted]  index
                                                                     search.bundle.js   114 KiB                                                                       search  [emitted]  search
                                                             single-channel.bundle.js  45.7 KiB                                                               single-channel  [emitted]  single-channel
                                                               single-topic.bundle.js    44 KiB                                                                 single-topic  [emitted]  single-topic
                                                               single-video.bundle.js   113 KiB                                                                 single-video  [emitted]  single-video
                                                               topic-videos.bundle.js  60.7 KiB                                                                 topic-videos  [emitted]  topic-videos
                                                                     topics.bundle.js   324 KiB                                                                       topics  [emitted]  topics
vendors~channel-about~channel-videos~index~search~single-video~topic-videos.bundle.js   103 KiB  vendors~channel-about~channel-videos~index~search~single-video~topic-videos  [emitted]  vendors~channel-about~channel-videos~index~search~single-video~topic-videos
       vendors~channel-videos~index~search~single-video~topic-videos~topics.bundle.js  31.3 KiB         vendors~channel-videos~index~search~single-video~topic-videos~topics  [emitted]  vendors~channel-videos~index~search~single-video~topic-videos~topics
                                                       vendors~single-video.bundle.js  51.9 KiB                                                         vendors~single-video  [emitted]  vendors~single-video
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js 52 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/vue-head/vue-head.js] 6.34 KiB {main} [built]
[./node_modules/vue-infinite-scroll/vue-infinite-scroll.js] 6.67 KiB {main} [built]
[./node_modules/vue-progressbar/dist/vue-progressbar.js] 5.97 KiB {main} [built]
[./node_modules/vue/dist/vue.runtime.esm.js] 222 KiB {main} [built]
[./node_modules/vue2-filters/dist/vue2-filters.js] 17.5 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./src/main.js] 607 bytes {main} [built]
    + 341 hidden modules
i ｢wdm｣: Compiled successfully.`

**Comment by freearhey** [comment]
Well, I personally do not see any errors. As I said earlier, I cannot reproduce the error, but maybe someone else has encountered the same problem and can help.

**Comment by mohsin1122** [comment]
:'(

**Comment by mohsin1122** [comment]
the Youtube api key in .env file should be inside double quotes(" ") or just the key?

**Comment by freearhey** [comment]
just the key

**Comment by mohsin1122** [comment]
its fixed.
i forgot to add `YOUTUBE_API_KEY=` before the key

**Comment by freearhey** [comment]
glad to hear it.
