### ISSUE TITLE
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "12.0", "14.0", "4.0".

### ISSUE THREAD

**Issue by Smilefounder** [freearhey/web-learn#2]
Hi,

Tried to run "npm i" at the first hit. And the error show as below:
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "12.0", "14.0", "4.0".

I tried to install MsBuild Tool 2013 but it doesn't help.

Thanks,
Huy

**Comment by Smilefounder** [comment]
Fixed by run 

`
npm install --global --production windows-build-tools
`

**Comment by lekevoid** [comment]
Thanks so much ! It worked for me too !
I had started having the problem after updating Node, and I made the mistake of installing all the extra stuff (chocolatey and such) which seems to have completely screwed up my VS/.NET install.

**Comment by ernanni** [comment]
I tried the same command, but it got stucked on the same message

`Python 2.7.16 is already installed, not installing again.`

should I uninstall python in order to get it going?

**Comment by iemwill** [comment]
> I tried the same command, but it got stucked on the same message
> 
> `Python 2.7.16 is already installed, not installing again.`
> 
> should I uninstall python in order to get it going?

did u try?

**Comment by ghost** [comment]
For anyone, who see this error and did not find solution. I found solution for my project.
I has node.js 12.x installed via Chocolatey. I uninstalled node.js version 12.x and installed node.js version 10.x from the installer at the official site.

**Comment by MikeKeane-Uni** [comment]
> I tried the same command, but it got stucked on the same message
> 
> `Python 2.7.16 is already installed, not installing again.`
> 
> should I uninstall python in order to get it going?

I thought I was stuck on this message too.  Just bear with it, it takes quite a long time!  I checked task manager and could see the cmd prompt was still working on something so I left it.  It took a while but it does get past this message.

**Comment by xin-chan** [comment]
I tried the same command，and also got Python 2.7.16 is already installed, not installing again.and then what  i do for solve it

**Comment by thefat32** [comment]
If you "get stuck" after python is already installed message. Just wait, it is not stuck.
